name: Telegram Mirror

on:
  schedule:
    - cron: "*/30 * * * *"   # هر 30 دقیقه
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run mirror
        env:
          TG_CHANNEL_URL: https://t.me/FVpnProxy
        run: |
          python mirror.py

      - name: Commit archive
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add data/posts.json

          git diff --cached --quiet || git commit -m "update telegram archive"

          git push
