name: Update Telegram Mirror

on:
  schedule:
    - cron: "0 */6 * * *"   # هر ۶ ساعت
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    # لازم برای git push
    permissions:
      contents: write

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true   # برای رفع error 128 اجباری است

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp beautifulsoup4

      - name: Run mirror.py
        run: python mirror.py

      - name: Git configure
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stage changes
        run: git add .

      - name: Check for changes
        id: changes
        run: |
          if git diff --cached --quiet; then
            echo "changed=no" >> $GITHUB_OUTPUT
          else
            echo "changed=yes" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.changes.outputs.changed == 'yes'
        run: |
          git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M:%S')"

      - name: Push changes
        if: steps.changes.outputs.changed == 'yes'
        run: git push origin HEAD:main
